title: Shibaprasad Bhattacharya
baseurl: ""
url: "https://shibaprasadb.github.io"
future: true

plugins:
  - jekyll-feed

excerpt_separator: <!--more-->

feed:
  path: feed.xml

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
