project:
  type: website

website:
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Publications
        href: publications.qmd
      - text: About
        href: about.qmd
      - text: Subscribe
        href: subscribe.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/shibaprasad-bhattacharya/
      - icon: github
        href: https://github.com/shibaprasadb

format:
  html:
    css: styles.css
    include-after-body:
      - partials/giscus.html
